development:
  adapter: postgresql
  encoding: unicode
  database: sparklingandwine_development
  pool: 5
  username: sparklingandwine
  password:
  # host: localhost

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: sparklingandwine_test
  pool: 5
  username: sparklingandwine
  password:
  # host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sparklingandwine_production
  pool: 5
  username: sparklingandwine
  password:
  # host: localhost
